### ISSUE TITLE
Uncaught Error: Class 'Sightengine\\SightengineClient' not found

### ISSUE THREAD

**Issue by AlexUrrutia** [Sightengine/client-php#2]
Hi, I tried installing your SDK but I can't get it to work, any idea? please help, I'm stuck

`PHP Fatal error:  Uncaught Error: Class 'Sightengine\\SightengineClient' not found in /var/www/html/photobooth/app.php
`

```
<?php
use \Sightengine\SightengineClient; 
$client = new SightengineClient('xxxxxxxx', 'xxxxxxxxxxxxxxxx');

```

**Comment by ghost** [comment]
Hi,

When installing using composer, you have to include the file in your code. 
For example:

`require_once 'vendor'.DIRECTORY_SEPARATOR.'autoload.php';`
