### ISSUE TITLE
guzzlehttp requirement

### ISSUE THREAD

**Issue by luisalonsobr** [Sightengine/client-php#5]
The requirement for guzzlehttp is out of dated and conflicting with newer packages with composer.

**Comment by jdppl** [comment]
It needs guzzlehttp/guzzle 7.2.0. I have installed that version. But still, it shows the following error.

Problem 1
    - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.2.0].
    - Can only install one of: guzzlehttp/guzzle[7.2.0, 6.5.x-dev].
    - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.2.0].
    - sightengine/client-php 1.3 requires guzzlehttp/guzzle ~6.0 -> satisfiable by guzzlehttp/guzzle[6.5.x-dev].
    - Installation request for sightengine/client-php ^1.3 -> satisfiable by sightengine/client-php[1.3].
    - Installation request for guzzlehttp/guzzle 7.2.0 -> satisfiable by guzzlehttp/guzzle[7.2.0].

**Comment by vesper8** [comment]
The problem is the composer.json explicitly requires `~6.0`

To fix, fork the project and then change that line to `"guzzlehttp/guzzle": "~6.0|~7.0"`

I've done it, it works

**Comment by davidlis** [comment]
Thank you very much for your comments. The package has been updated with up-to-date dependencies.
