### ISSUE TITLE
composer error in Laravel 9

### ISSUE THREAD

**Issue by saschagysel** [Sightengine/client-php#7]
Tried to install this package in Laravel 9 with composer and got the following error:

`  Problem 1
    - Root composer.json requires sightengine/client-php ^1.3 -> satisfiable by sightengine/client-php[1.3].
    - sightengine/client-php 1.3 requires guzzlehttp/guzzle ~6.0 -> found guzzlehttp/guzzle[6.0.0, ..., 6.5.x-dev] but it conflicts with your root composer.json require (^7.2).`

Seems to be a problem with the requirement of Guzzle (7.0 by the package / 7.2 by Laravel).

Could you please update the package to make it compatible with the newest Laravel version. Thanks.

**Comment by zizther** [comment]
Also need to support `guzzlehttp/guzzle` 7.2+ Would be good to get the package requirements updated.

**Comment by davidlis** [comment]
Thank you very much for your comments. The package has now been updated with a >7 Guzzle requirement.
